const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const MANAGED_BLOCK_START = '# >>> MCP-MANAGER START >>>';
const MANAGED_BLOCK_END = '# <<< MCP-MANAGER END <<<';

function ensureParentDir(filePath) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function tomlString(value) {
  return JSON.stringify(String(value ?? ''));
}

function tomlKey(key) {
  const plain = /^[A-Za-z0-9_-]+$/.test(key);
  return plain ? key : tomlString(key);
}

function sanitizeAlias(name, fallback) {
  const base = String(name || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  return base || fallback;
}

function buildAliasMap(state) {
  const aliases = {};
  const used = new Set();

  state.servers.forEach((server, index) => {
    const fallback = `mcp-${index + 1}`;
    const base = sanitizeAlias(server.name, fallback);

    let alias = base;
    let counter = 2;
    while (used.has(alias)) {
      alias = `${base}-${counter}`;
      counter += 1;
    }

    used.add(alias);
    aliases[server.id] = alias;
  });

  return aliases;
}

function getEnabledEntriesForTool(state, tool, aliasMap) {
  return state.servers
    .filter((server) => Boolean((state.matrix[server.id] || {})[tool.id]))
    .map((server) => ({
      alias: aliasMap[server.id],
      server,
    }));
}

function getManagedAliasSet(aliasMap) {
  return new Set(Object.values(aliasMap));
}

function serverForStdio(server) {
  return {
    command: server.command || '',
    args: Array.isArray(server.args) ? server.args : [],
    env: server.env && typeof server.env === 'object' ? server.env : {},
    cwd: server.cwd || '',
  };
}

function writeCodexToml(state, tool, enabledEntries) {
  const targetPath = tool.configPath;
  ensureParentDir(targetPath);

  const existing = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf-8') : '';
  const block = renderCodexManagedBlock(enabledEntries);

  const pattern = new RegExp(
    `${escapeRegExp(MANAGED_BLOCK_START)}[\\s\\S]*?${escapeRegExp(MANAGED_BLOCK_END)}\\n?`,
    'm'
  );

  let nextContent = '';
  if (pattern.test(existing)) {
    nextContent = existing.replace(pattern, `${block}\n`);
  } else if (existing.trim().length > 0) {
    nextContent = `${existing.replace(/\s*$/, '')}\n\n${block}\n`;
  } else {
    nextContent = `${block}\n`;
  }

  fs.writeFileSync(targetPath, nextContent, 'utf-8');

  return {
    toolId: tool.id,
    ok: true,
    path: targetPath,
    count: enabledEntries.length,
    format: 'codex_toml',
  };
}

function renderCodexManagedBlock(enabledEntries) {
  const lines = [MANAGED_BLOCK_START, '# This section is generated by MCP Manager.'];

  for (const item of enabledEntries) {
    const server = serverForStdio(item.server);
    const tableName = tomlKey(item.alias);

    lines.push('');
    lines.push(`[mcp_servers.${tableName}]`);
    lines.push(`command = ${tomlString(server.command)}`);
    lines.push(`args = [${server.args.map((arg) => tomlString(arg)).join(', ')}]`);

    const envEntries = Object.entries(server.env)
      .filter(([key]) => key)
      .map(([key, value]) => `${tomlKey(String(key))} = ${tomlString(String(value))}`);
    lines.push(`env = { ${envEntries.join(', ')} }`);
  }

  lines.push('');
  lines.push(MANAGED_BLOCK_END);

  return lines.join('\n');
}

function readJsonObject(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf-8').trim();
  if (!content) {
    return {};
  }

  const parsed = JSON.parse(content);
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('Config root must be a JSON object');
  }

  return parsed;
}

function writeJsonObject(filePath, obj) {
  ensureParentDir(filePath);
  fs.writeFileSync(filePath, JSON.stringify(obj, null, 2), 'utf-8');
}

function writeClaudeProjectJson(state, tool, enabledEntries, managedAliases) {
  const targetPath = tool.configPath;
  const config = readJsonObject(targetPath);

  if (!config.mcpServers || typeof config.mcpServers !== 'object' || Array.isArray(config.mcpServers)) {
    config.mcpServers = {};
  }

  for (const alias of managedAliases) {
    delete config.mcpServers[alias];
  }

  for (const item of enabledEntries) {
    const server = serverForStdio(item.server);
    config.mcpServers[item.alias] = {
      command: server.command,
      args: server.args,
      env: server.env,
    };
  }

  writeJsonObject(targetPath, config);

  return {
    toolId: tool.id,
    ok: true,
    path: targetPath,
    count: enabledEntries.length,
    format: 'claude_project_json',
  };
}

function writeGeminiProjectJson(state, tool, enabledEntries, managedAliases) {
  const targetPath = tool.configPath;
  const config = readJsonObject(targetPath);

  if (!config.mcpServers || typeof config.mcpServers !== 'object' || Array.isArray(config.mcpServers)) {
    config.mcpServers = {};
  }

  for (const alias of managedAliases) {
    delete config.mcpServers[alias];
  }

  for (const item of enabledEntries) {
    const server = serverForStdio(item.server);
    const payload = {
      command: server.command,
      args: server.args,
      env: server.env,
    };

    if (server.cwd) {
      payload.cwd = server.cwd;
    }

    config.mcpServers[item.alias] = payload;
  }

  writeJsonObject(targetPath, config);

  return {
    toolId: tool.id,
    ok: true,
    path: targetPath,
    count: enabledEntries.length,
    format: 'gemini_project_json',
  };
}

function parseCodexConfiguredAliases(content) {
  const aliases = new Set();

  const quotedRe = /^\[mcp_servers\."([^"]+)"\]\s*$/gm;
  let match = quotedRe.exec(content);
  while (match) {
    aliases.add(match[1]);
    match = quotedRe.exec(content);
  }

  const bareRe = /^\[mcp_servers\.([A-Za-z0-9_-]+)\]\s*$/gm;
  match = bareRe.exec(content);
  while (match) {
    aliases.add(match[1]);
    match = bareRe.exec(content);
  }

  return [...aliases];
}

function readConfiguredAliases(tool) {
  if (!fs.existsSync(tool.configPath)) {
    return [];
  }

  if (tool.format === 'codex_toml') {
    const content = fs.readFileSync(tool.configPath, 'utf-8');
    return parseCodexConfiguredAliases(content);
  }

  const config = readJsonObject(tool.configPath);
  const servers = config.mcpServers;
  if (!servers || typeof servers !== 'object' || Array.isArray(servers)) {
    return [];
  }

  return Object.keys(servers);
}

function resolveCliPath(command) {
  const result = spawnSync('which', [command], {
    encoding: 'utf-8',
    timeout: 2000,
  });

  if (result.status !== 0) {
    return '';
  }

  return String(result.stdout || '').trim().split('\n')[0];
}

function runCliVerification(tool, enabledAliases) {
  if (!tool.verifyArgs || tool.verifyArgs.length === 0) {
    return {
      attempted: false,
      ok: null,
      output: '',
      matched: [],
    };
  }

  const result = spawnSync(tool.cliCommand, tool.verifyArgs, {
    cwd: process.cwd(),
    encoding: 'utf-8',
    timeout: 5000,
  });

  const output = `${result.stdout || ''}\n${result.stderr || ''}`;
  const matched = enabledAliases.filter((alias) => output.includes(alias));
  const commandOk = result.status === 0;
  const ok = commandOk && matched.length === enabledAliases.length;

  return {
    attempted: true,
    ok,
    output: output.trim(),
    exitCode: result.status,
    matched,
  };
}

function diagnoseTool(state, tool, aliasMap) {
  const managedAliases = getManagedAliasSet(aliasMap);
  const enabledEntries = getEnabledEntriesForTool(state, tool, aliasMap);
  const enabledAliases = enabledEntries.map((item) => item.alias);

  const cliPath = resolveCliPath(tool.cliCommand);
  const cliInstalled = Boolean(cliPath);
  const configExists = fs.existsSync(tool.configPath);

  let configuredAliases = [];
  let parseError = '';

  try {
    configuredAliases = readConfiguredAliases(tool);
  } catch (error) {
    parseError = error.message;
  }

  const configuredSet = new Set(configuredAliases);
  const missingEnabled = enabledAliases.filter((alias) => !configuredSet.has(alias));

  const managedButDisabled = [...managedAliases].filter(
    (alias) => configuredSet.has(alias) && !enabledAliases.includes(alias)
  );
  const unmanagedConfigured = configuredAliases.filter((alias) => !managedAliases.has(alias));

  const cliVerification = cliInstalled
    ? runCliVerification(tool, enabledAliases)
    : {
        attempted: false,
        ok: null,
        output: '',
        matched: [],
      };

  let status = 'effective';
  let summary = '配置生效';

  if (!cliInstalled) {
    status = 'not_effective';
    summary = `未检测到 ${tool.cliCommand} 命令`;
  } else if (parseError) {
    status = 'not_effective';
    summary = `配置文件解析失败: ${parseError}`;
  } else if (missingEnabled.length > 0 || managedButDisabled.length > 0) {
    status = 'partial';
    summary = '配置与开关矩阵不一致';
  } else if (cliVerification.attempted && cliVerification.ok === false) {
    status = 'partial';
    summary = 'CLI 探测未完全匹配，建议再次同步后复检';
  }

  return {
    toolId: tool.id,
    toolName: tool.name,
    cliCommand: tool.cliCommand,
    cliPath,
    cliInstalled,
    status,
    summary,
    officialPath: tool.officialPath,
    configPath: tool.configPath,
    pathIsOfficial: path.resolve(tool.officialPath) === path.resolve(tool.configPath),
    configExists,
    enabledCount: enabledAliases.length,
    enabledAliases,
    configuredCount: configuredAliases.length,
    configuredAliases,
    unmanagedConfigured,
    missingEnabled,
    managedButDisabled,
    parseError,
    cliVerification,
  };
}

function writeToolConfig(state, tool, aliasMap) {
  const enabledEntries = getEnabledEntriesForTool(state, tool, aliasMap);
  const managedAliases = getManagedAliasSet(aliasMap);

  if (tool.format === 'codex_toml') {
    return writeCodexToml(state, tool, enabledEntries);
  }

  if (tool.format === 'claude_project_json') {
    return writeClaudeProjectJson(state, tool, enabledEntries, managedAliases);
  }

  if (tool.format === 'gemini_project_json') {
    return writeGeminiProjectJson(state, tool, enabledEntries, managedAliases);
  }

  return {
    toolId: tool.id,
    ok: false,
    message: `Unsupported tool format: ${tool.format}`,
  };
}

function syncAllToolConfigs(state) {
  const aliasMap = buildAliasMap(state);
  const results = state.tools.map((tool) => {
    try {
      return writeToolConfig(state, tool, aliasMap);
    } catch (error) {
      return {
        toolId: tool.id,
        ok: false,
        message: error.message,
      };
    }
  });

  const diagnostics = state.tools.map((tool) => diagnoseTool(state, tool, aliasMap));

  return {
    timestamp: new Date().toISOString(),
    aliasMap,
    results,
    diagnostics,
  };
}

function scanToolDiagnostics(state) {
  const aliasMap = buildAliasMap(state);
  const diagnostics = state.tools.map((tool) => diagnoseTool(state, tool, aliasMap));

  return {
    timestamp: new Date().toISOString(),
    aliasMap,
    diagnostics,
  };
}

module.exports = {
  syncAllToolConfigs,
  scanToolDiagnostics,
};
